#apiVersion: v1
#kind: Secret
#metadata:
#  name: tls-secret
#  namespace: argocd
#type: kubernetes.io/tls
# workss
#data:
#  server.crt: |
#       encoded.crt
#  server.key: |
#       encoded.key
#
#---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
    host: argocd.ekong.xyz
  tls:
  - hosts:
    - argocd.ekong.xyz
    secretName: tls-secret

#spec:
#  tls:
#    - hosts:
#      - "*.ekong.xyz"
#      # This assumes tls-secret exists and the SSL
#      # certificate contains a CN for argocd.ekong.xyz
#      secretName: tls-secret    
#  - host: "argocd.ekong.xyz"
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: argocd-server
#            port:
#              number: 80
